### ISSUE TITLE
Error 403 while installing module

### ISSUE THREAD

**Issue by 7coil** [pandres95/ndi.js#4]
An error `403` is encountered whilst attempting to install the package from https://ndijs.s3.us-east-2.amazonaws.com/ndi/v1.0.5/Release/linux-x64.tar.gz

If you're wondering, I'm using WSL and tried Node 16.14.0 and Node 17.5.0

**Comment by pandres95** [comment]
Hey @7coil!

This error was ocurring because I hadn't uploaded the binaries for _linux-x64_. Already done, via GitHub Actions. Let me know if you find something new on your side!

**Comment by 7coil** [comment]
Hurray! - I'll see what the world of NDI has to offer later
